### ISSUE TITLE
Mission ideas

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-core#10]
Discussion on what kind of missions we could do

**Comment by SyMP2005** [comment]
@Omnirock

**Comment by Omnirock** [comment]
1) Checkpoint Security - Setup a checkpoint station into a city, inspecting vehicles for contraband/explosive devices. 
2) VIP escort/security - Pick up a VIP and his party landing in at one of the airports, safely them to a pre determined location. 
3) Logistics Setup - Securing and setting up an FOB/Secure location in a hostile environment. would involve moving multiple pieces of equipment while being mindful of IEDs and roadside ambushes.
4) Recon and Intelligence gathering - Observe and report, don't get spotted, or the mission is compromised. 
5) QRF - Theseus would be deployed quickly to aid in civilian distress as required. These missions would require quick actions and deploying as quickly as possible to avoid additional civilian casualties. 
6) Maritime Patrol - Patrolling the coast for pirate activity, inspecting cargo, intercepting narcos.

I have a few more detailed mission ideas as well. And depending on if we want to break the Geneva convention or not.. some ideas for that as well.

**Comment by SyMP2005** [comment]
Great ideas!

A technical question; how would you "inspect" the vehicles? *technically*?

**Comment by SyMP2005** [comment]
moved to forum
