### ISSUE TITLE
Redefine Armory items

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-core#13]
Allow certain items (mostly clothing depending on position.
- [x] recruit position
- [x] contractor position
- [x] specialist & higher position

**Comment by SyMP2005** [comment]
Need to cut down WAY on items / role/rank

**Comment by jonpas** [comment]
@SyMP2005 status?

**Comment by SyMP2005** [comment]
Also done a while ago, again my bad!
