### ISSUE TITLE
Create dynamic roster page

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-core#22]
- [x] Automatically add player when joining
- [x] Assign them with: Recruit / Contractor / Senior-Contractor
- [x] Display profile info from public fields
- [x] Automatically remove people who are set to retired

**Comment by Omnirock** [comment]
Started some work on this, building custom views and trying to get names to display correctly.

**Comment by SyMP2005** [comment]
Nice!

Non priority though ;)

**Comment by Omnirock** [comment]
the view for this is working and showing the correct info... it's just not showing names correctly.

**Comment by jonpas** [comment]
This has been done for a few months now by @mikecorello.
