### ISSUE TITLE
Remake Wake island content to Stratis

### ISSUE THREAD

**Issue by SyMP2005** [Theseus-Aegis/tac-a3-core#7]
*For Olympus*

- [x] Pistol range
- [x] SMG range
- [x] Rifle MG range
- [x] DMR range with buildings of Kamino firing range-

- [x] Movement course
- [x] General purpose area
- [x] Launcher range
- [x] Basic training

**Comment by jonpas** [comment]
Done in e221dda5f2ce181bf397635f712bb71acf1d626e
